# _AI POWERED SPAM CLASSIFIER_

In [4]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import shuffle

## _Loading the Dataset_

In [5]:
data = pd.read_csv('spam.csv', encoding='latin-1')

In [6]:
data

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

## _Preprocessing the Dataset_

In [7]:
# Drop unnecessary columns

data = data.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1)

In [8]:
data

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [9]:
# Rename columns for clarity

data.columns = ['label', 'message']

In [10]:
# Shuffle the dataset

data = shuffle(data)

In [11]:
# Preprocess the text data

def preprocess_text(text):
    
    # Convert text to lowercase
    
    text = text.lower()
    
    # Tokenize the text (split it into individual words)
    
    tokens = text.split()
    
    # Remove special characters, punctuation, and numbers
    
    tokens = [word for word in tokens if word.isalpha()]
    
    # Remove common stop words (optional)
    # You can use NLTK or SpaCy for more extensive stop word removal
    # tokens = [word for word in tokens if word not in stopwords]
    # Rejoin the tokens into a single string
    
    text = ' '.join(tokens)
    
    return text

data['message'] = data['message'].apply(preprocess_text)

In [12]:
data

     label                                            message
3504   ham                          life alle oru pole allalo
2503   ham  fwiw the reason only around when time to smoke...
988    ham  yun ubi one say if wan call by look for only g...
3449   ham                            ya just telling abt tht
2655   ham                               i have to run now so
...    ...                                                ...
1587   ham  dont search let love find thats why its called...
1713  spam  hard live chat just choose your girl and conne...
2138   ham                             k still are you loving
4023   ham                                       wat time wan
1366   ham          bbq this sat at mine from ur welcome come

[5572 rows x 2 columns]

In [13]:
# Encode the labels (spam as 1, ham as 0)

le = LabelEncoder()
data['label'] = le.fit_transform(data['label'])

## _Train the Model_

In [14]:
# Split the dataset into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(data['message'], data['label'], test_size=0.25)

In [15]:
X_train

1392            thk shld b i wana go can go for one whole
4514    that was random saw my old roomate on he gradu...
2477    i hope your next space gives you everything yo...
5342    u r subscribed textcomp wkly free question sub...
2259                        ill call you evening ill some
                              ...
1590    somewhr someone is surely made and god has dec...
5193                                      you in tampa or
1222                       teach me apps when you come to
201     hello darlin ive finished college now so txt m...
1023                             may i call you later pls
Name: message, Length: 4179, dtype: object

In [16]:
y_train

1392    0
4514    0
2477    0
5342    1
2259    0
       ..
1590    0
5193    0
1222    0
201     0
1023    0
Name: label, Length: 4179, dtype: int32

In [17]:
# TF-IDF Vectorization

tfidf_vectorizer = TfidfVectorizer(max_features=5000)
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [18]:
X_train_tfidf,X_test_tfidf

(<4179x5000 sparse matrix of type '<class 'numpy.float64'>'
 	with 42468 stored elements in Compressed Sparse Row format>,
 <1393x5000 sparse matrix of type '<class 'numpy.float64'>'
 	with 13242 stored elements in Compressed Sparse Row format>)

## _Accuracy_

In [21]:
from sklearn.metrics import accuracy_score

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

# Display the accuracy
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 95.48%