# _AI POWERED SPAM CLASSIFIER_

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import shuffle

## _Loading the Dataset_

In [2]:
data = pd.read_csv('spam.csv', encoding='latin-1')

In [3]:
data

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

## _Preprocessing the Dataset_

In [4]:
# Drop unnecessary columns

data = data.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1)

In [5]:
data

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [6]:
# Rename columns for clarity

data.columns = ['label', 'message']

In [7]:
# Shuffle the dataset

data = shuffle(data)

In [8]:
# Preprocess the text data

def preprocess_text(text):
    
    # Convert text to lowercase
    
    text = text.lower()
    
    # Tokenize the text (split it into individual words)
    
    tokens = text.split()
    
    # Remove special characters, punctuation, and numbers
    
    tokens = [word for word in tokens if word.isalpha()]
    
    # Remove common stop words (optional)
    # You can use NLTK or SpaCy for more extensive stop word removal
    # tokens = [word for word in tokens if word not in stopwords]
    # Rejoin the tokens into a single string
    
    text = ' '.join(tokens)
    
    return text

data['message'] = data['message'].apply(preprocess_text)

In [9]:
data

     label                                            message
606   spam  soiree speciale zouk with nichols from roses a...
2220   ham  but really quite funny lor then u shd haf run ...
1225   ham  you will receive the account no another sorry ...
3011   ham  yeah no probs last night is obviously catching...
3783   ham            dear got train and seat mine lower seat
...    ...                                                ...
5130   ham                     any way where are you and what
262    ham                          my in luton ring me if ur
3277   ham                                   what happened in
2814   ham          some are lasting as much as you might get
2612   ham                                       all innocent

[5572 rows x 2 columns]

In [10]:
# Encode the labels (spam as 1, ham as 0)

le = LabelEncoder()
data['label'] = le.fit_transform(data['label'])

## _Train the Model_

In [11]:
# Split the dataset into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(data['message'], data['label'], test_size=0.25)

In [12]:
X_train

2684                       oredi booked slots my weekends
100     okay name ur price as long as its wen can i pi...
3993    i love to i want to hold you in my strong arms...
2847    sad story of a man last week was my my wife wi...
1254                                   what your plan for
                              ...
4203                  how are you enjoying this take care
2150                              the waiting by the tree
367     here is your discount code to stop further mes...
2756    have a good watch out for remember when you ge...
281                                        u miss someone
Name: message, Length: 4179, dtype: object

In [13]:
y_train

2684    0
100     0
3993    0
2847    0
1254    0
       ..
4203    0
2150    0
367     1
2756    0
281     0
Name: label, Length: 4179, dtype: int32

In [14]:
# TF-IDF Vectorization

tfidf_vectorizer = TfidfVectorizer(max_features=5000)
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [15]:
X_train_tfidf,X_test_tfidf

(<4179x5000 sparse matrix of type '<class 'numpy.float64'>'
 	with 42254 stored elements in Compressed Sparse Row format>,
 <1393x5000 sparse matrix of type '<class 'numpy.float64'>'
 	with 13482 stored elements in Compressed Sparse Row format>)